# Generated by Django 2.2.16 on 2020-11-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_document_current_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='colour',
        ),
    ]
