#!/bin/bash
IMAGE_NAME="jaymedh/paperless"

if [ "${DOCKER_USERNAME}" == "" -o "${DOCKER_PASSWORD}" == "" ]
then
    exit 0
fi

echo "$DOCKER_PASSWORD" | docker login --username=${DOCKER_USERNAME} --password-stdin
docker push ${IMAGE_NAME}:${TRAVIS_COMMIT}

if [ "${TRAVIS_TAG}" != "" ]
then
    IMAGE_TAG=$TRAVIS_TAG
elif [ "${TRAVIS_BRANCH}" == "master" ]
then
    IMAGE_TAG="latest"
else
    exit 0
fi

docker tag ${IMAGE_NAME}:${TRAVIS_COMMIT} ${IMAGE_NAME}:${IMAGE_TAG}
docker push ${IMAGE_NAME}:${IMAGE_TAG}